routes:
  /signup/: 
    template: members/signup
    # data: page.signup # When active data will be taken from the  "/signup/" page
  /signin/: 
    template: members/signin
    # data: page.signin # When active data will be taken from the  "/signin/" page
  /account/: 
    template: members/account 
    # data: page.account # When active data will be taken from the  "/account/" page
  /archive/:
    controller: channel
    template: archive
    data: page.archive
  /recommendations/:
    template: recommend
    # data: page.recommendations # When active data will be taken from the  "/recommendations/" page

collections:
  /:
    permalink: /{slug}/
    template: index
  
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
